package com.example.java25demo.hero;

import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class CoolHeroService {

    public List<CoolHero> getCoolHeroes() {
        return List.of(
                CoolHero.builder()
                        .name("Nova Blaze")
                        .alias("Solar Phoenix")
                        .experienceLevel(850)
                        .heightCm(188)
                        .weightKg(92.5)
                        .primaryPower("Solar flares and radiant shields")
                        .homeBase("Helios Station")
                        .build(),
                CoolHero.builder()
                        .name("Shadow Lynx")
                        .alias("Night Prowler")
                        .experienceLevel(640)
                        .heightCm(172)
                        .weightKg(68.0)
                        .primaryPower("Stealth field and acrobatics")
                        .homeBase("Neo City rooftops")
                        .build(),
                CoolHero.builder()
                        .name("Circuit Guardian")
                        .alias("Volt Sentinel")
                        .experienceLevel(910)
                        .heightCm(195)
                        .weightKg(104.3)
                        .primaryPower("Electro-kinetic barriers and hacking")
                        .homeBase("Arc Core Spire")
                        .build(),
                CoolHero.builder()
                        .name("Terra Vanguard")
                        .alias("Earthshaper")
                        .experienceLevel(720)
                        .heightCm(183)
                        .weightKg(96.0)
                        .primaryPower("Seismic control and stone armor")
                        .homeBase("Bastion Outpost")
                        .build(),
                CoolHero.builder()
                        .name("Aqua Pulse")
                        .alias("Tideweaver")
                        .experienceLevel(430)
                        .heightCm(169)
                        .weightKg(61.2)
                        .primaryPower("Water shaping and hydro jets")
                        .homeBase("Pelagia Dome")
                        .build(),
                CoolHero.builder()
                        .name("Ember Spark")
                        .alias("Cinder Scout")
                        .experienceLevel(120)
                        .heightCm(165)
                        .weightKg(58.5)
                        .primaryPower("Flash ignition and ember darts")
                        .homeBase("Crimson Camp")
                        .build(),
                CoolHero.builder()
                        .name("Iron Warden")
                        .alias("Steel Bulwark")
                        .experienceLevel(560)
                        .heightCm(201)
                        .weightKg(118.0)
                        .primaryPower("Magnetic shields and heavy armor")
                        .homeBase("Forge Citadel")
                        .build(),
                CoolHero.builder()
                        .name("Cloud Dancer")
                        .alias("Skystride")
                        .experienceLevel(305)
                        .heightCm(176)
                        .weightKg(70.4)
                        .primaryPower("Aerial agility and wind gusts")
                        .homeBase("Nimbus Peak")
                        .build(),
                CoolHero.builder()
                        .name("Rift Runner")
                        .alias("Blink")
                        .experienceLevel(990)
                        .heightCm(180)
                        .weightKg(73.0)
                        .primaryPower("Short-range teleport and phase shift")
                        .homeBase("Phase Gate Lab")
                        .build(),
                CoolHero.builder()
                        .name("Chrono Archer")
                        .alias("Timebound")
                        .experienceLevel(680)
                        .heightCm(186)
                        .weightKg(83.7)
                        .primaryPower("Temporal arrows and slowed fields")
                        .homeBase("Eon Range")
                        .build(),
                CoolHero.builder()
                        .name("Lumen Ranger")
                        .alias("Glare")
                        .experienceLevel(255)
                        .heightCm(174)
                        .weightKg(66.8)
                        .primaryPower("Hard light constructs and tracking")
                        .homeBase("Beacon Verge")
                        .build(),
                CoolHero.builder()
                        .name("Storm Herald")
                        .alias("Thunderborne")
                        .experienceLevel(775)
                        .heightCm(192)
                        .weightKg(99.1)
                        .primaryPower("Thunder calls and storm control")
                        .homeBase("Tempest Tower")
                        .build(),
                CoolHero.builder()
                        .name("Polar Shade")
                        .alias("Frost Veil")
                        .experienceLevel(95)
                        .heightCm(170)
                        .weightKg(62.3)
                        .primaryPower("Cryokinesis and mist screens")
                        .homeBase("Glacier Hollow")
                        .build(),
                CoolHero.builder()
                        .name("Granite Wolf")
                        .alias("Stoneclaw")
                        .experienceLevel(610)
                        .heightCm(190)
                        .weightKg(102.0)
                        .primaryPower("Stone skin and shockwave roars")
                        .homeBase("Howl Ridge")
                        .build(),
                CoolHero.builder()
                        .name("Quantum Skipper")
                        .alias("Slipstream")
                        .experienceLevel(45)
                        .heightCm(168)
                        .weightKg(59.4)
                        .primaryPower("Micro jumps through space-time")
                        .homeBase("Drift Harbor")
                        .build(),
                CoolHero.builder()
                        .name("Neon Ronin")
                        .alias("Bladeflash")
                        .experienceLevel(845)
                        .heightCm(182)
                        .weightKg(79.9)
                        .primaryPower("Energy katana and afterimage dashes")
                        .homeBase("Kyoto Sprawl")
                        .build(),
                CoolHero.builder()
                        .name("Starlit Mystic")
                        .alias("Astral Guide")
                        .experienceLevel(150)
                        .heightCm(171)
                        .weightKg(64.0)
                        .primaryPower("Starfield visions and astral wards")
                        .homeBase("Celestium Observatory")
                        .build(),
                CoolHero.builder()
                        .name("Plasma Diver")
                        .alias("Ion Drift")
                        .experienceLevel(905)
                        .heightCm(184)
                        .weightKg(87.6)
                        .primaryPower("Plasma lances and zero-G maneuvers")
                        .homeBase("Orbital Arc Hub")
                        .build(),
                CoolHero.builder()
                        .name("Mirage Strider")
                        .alias("Sandstep")
                        .experienceLevel(370)
                        .heightCm(178)
                        .weightKg(71.5)
                        .primaryPower("Illusory doubles and dune glide")
                        .homeBase("Shifting Expanse")
                        .build(),
                CoolHero.builder()
                        .name("Arcane Courier")
                        .alias("Runic Relay")
                        .experienceLevel(50)
                        .heightCm(167)
                        .weightKg(57.9)
                        .primaryPower("Spell carrying and glyph bursts")
                        .homeBase("Sigil Market")
                        .build(),
                CoolHero.builder()
                        .name("Void Whisper")
                        .alias(null)
                        .experienceLevel(0)
                        .heightCm(175)
                        .weightKg(69.0)
                        .primaryPower("Silencing fields and gravity folds")
                        .homeBase("Obsidian Quietus")
                        .build(),
                CoolHero.builder()
                        .name("Emberline Helix")
                        .alias("Spiral")
                        .experienceLevel(515)
                        .heightCm(179)
                        .weightKg(76.2)
                        .primaryPower("Spinning flame whips and coil leaps")
                        .homeBase("Helix Yard")
                        .build(),
                CoolHero.builder()
                        .name("Spiral Falcon")
                        .alias("Spiral")
                        .experienceLevel(515)
                        .heightCm(179)
                        .weightKg(76.2)
                        .primaryPower("Spinning flame whips and coil leaps")
                        .homeBase("Helix Yard")
                        .build(),
                CoolHero.builder()
                        .name("Horizon Falcon")
                        .alias("Skyblade")
                        .experienceLevel(525)
                        .heightCm(191)
                        .weightKg(90.7)
                        .primaryPower("Jet-assisted flight and aerial blades")
                        .homeBase("Sunrise Carrier")
                        .build(),
                CoolHero.builder()
                        .name("Cobalt Sentry")
                        .alias("Azure Guard")
                        .experienceLevel(1000)
                        .heightCm(198)
                        .weightKg(110.5)
                        .primaryPower("Tactical AI armor and power shields")
                        .homeBase("Blue Bastille")
                        .build(),
                CoolHero.builder()
                        .name("Cobalt Sentry2")
                        .alias("Azure Guard2")
                        .experienceLevel(15)
                        .heightCm(198)
                        .weightKg(110.5)
                        .primaryPower("Tactical AI armor and power shields")
                        .homeBase("Blue Bastille")
                        .build(),
                CoolHero.builder()
                        .name("Solaris Oracle")
                        .alias("Dayseer")
                        .experienceLevel(470)
                        .heightCm(177)
                        .weightKg(72.1)
                        .primaryPower("Precognitive flares and light wards")
                        .homeBase("Sunwell Terrace")
                        .build()
        );
    }
}
